package mutuelle_backend.entity;

public enum Role {

    SUPER_ADMIN,

    RESPONSABLE_SERVICE_SOCIAL,

    RESPONSABLE_BUREAU_ORDRE,
    RESPONSABLE_MUTUELLE,
    RESPONSABLE_ASSISTANCE,
    RESPONSABLE_CULTURE,
    RESPONSABLE_RETRAITES,
    RESPONSABLE_DECES,
    RESPONSABLE_ASSURANCE,

    AGENT
}