spring.application.name=mutuelle-backend

spring.datasource.url=jdbc:h2:mem:service_social;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=Y2hhbmdlLXRoaXMtdG8tYS1sb25nLXByb2R1Y3Rpb24tc2VjcmV0LWtleS0zMi1ieXRlcw==
app.jwt.expiration-minutes=480

server.port=8081