package mutuelle_backend.service;
import java.util.*; import lombok.RequiredArgsConstructor; import mutuelle_backend.dto.*; import mutuelle_backend.entity.Adherent; import mutuelle_backend.exception.*; import mutuelle_backend.repository.AdherentRepository; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class AdherentService {
 private final AdherentRepository repository;
 public Page<AdherentResponse> list(String search,String categorie,String situation,Pageable p){Specification<Adherent>s=(r,q,c)->c.conjunction();if(search!=null&&!search.isBlank()){String v="%"+search.toLowerCase(Locale.ROOT).trim()+"%";s=s.and((r,q,c)->c.or(c.like(c.lower(r.get("nomAr")),v),c.like(c.lower(r.get("prenomAr")),v),c.like(c.lower(r.get("matricule")),v),c.like(c.lower(r.get("matriculeBR")),v),c.like(c.lower(r.get("cin")),v)));}if(categorie!=null&&!categorie.isBlank())s=s.and((r,q,c)->c.equal(r.get("categorie"),categorie));if(situation!=null&&!situation.isBlank())s=s.and((r,q,c)->c.equal(r.get("situationCategorie"),situation));return repository.findAll(s,p).map(this::toResponse);}
 public AdherentResponse get(Long id){return toResponse(required(id));}
 @Transactional public AdherentResponse create(AdherentRequest r){validateUnique(r,null);return toResponse(repository.save(fromRequest(new Adherent(),r)));}
 @Transactional public AdherentResponse update(Long id,AdherentRequest r){Adherent a=required(id);validateUnique(r,id);return toResponse(repository.save(fromRequest(a,r)));}
 @Transactional public void delete(Long id){repository.delete(required(id));}
 public AdherentStatistics statistics(){var all=repository.findAll();return new AdherentStatistics(all.size(),all.stream().filter(a->"Actif".equalsIgnoreCase(a.getSituationCategorie())).count(),all.stream().filter(a->"Retraité".equalsIgnoreCase(a.getSituationCategorie())||"Retraite".equalsIgnoreCase(a.getSituationCategorie())).count(),all.stream().filter(Adherent::isPension).count());}
 private Adherent required(Long id){return repository.findById(id).orElseThrow(()->new NotFoundException("Adherent not found: "+id));}
 private void validateUnique(AdherentRequest r,Long id){Long x=id==null?-1L:id;if(repository.existsByMatriculeAndIdNot(r.matricule(),x))throw new ConflictException("Matricule already exists");if(repository.existsByCinAndIdNot(r.cin(),x))throw new ConflictException("CIN already exists");}
 private Adherent fromRequest(Adherent a,AdherentRequest r){a.setPrenomAr(r.prenomAr());a.setNomAr(r.nomAr());a.setCategorie(r.categorie());a.setGrade(r.grade());a.setMatriculeBR(r.matriculeBR());a.setMatricule(r.matricule());a.setDateNaissance(r.dateNaissance());a.setLieuNaissance(r.lieuNaissance());a.setDateRadiation(r.dateRadiation());a.setMotifRadiation(r.motifRadiation());a.setDateDeces(r.dateDeces());a.setCauseDeces(r.causeDeces());a.setDernierUnite(r.dernierUnite());a.setFormationUnite(r.formationUnite());a.setTelephone1(r.telephone1());a.setTelephone2(r.telephone2());a.setAdresse(r.adresse());a.setEmail(r.email());a.setSituationCategorie(r.situationCategorie());a.setPension(r.pension());a.setCin(r.cin());return a;}
 private AdherentResponse toResponse(Adherent a){return new AdherentResponse(a.getId(),a.getPrenomAr(),a.getNomAr(),a.getCategorie(),a.getGrade(),a.getMatriculeBR(),a.getMatricule(),a.getDateNaissance(),a.getLieuNaissance(),a.getDateRadiation(),a.getMotifRadiation(),a.getDateDeces(),a.getCauseDeces(),a.getDernierUnite(),a.getFormationUnite(),a.getTelephone1(),a.getTelephone2(),a.getAdresse(),a.getEmail(),a.getSituationCategorie(),a.isPension(),a.getCin());}
}
