spring.application.name=mutuelle-backend

# =====================================================
# DATABASE H2 - PERSISTANTE
# =====================================================

spring.datasource.url=jdbc:h2:file:./data/service_social;MODE=PostgreSQL;AUTO_SERVER=TRUE

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# H2 CONSOLE
# =====================================================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =====================================================
# JWT
# =====================================================

app.jwt.secret=Y2hhbmdlLXRoaXMtdG8tYS1sb25nLXByb2R1Y3Rpb24tc2VjcmV0LWtleS0zMi1ieXRlcw==

app.jwt.expiration-minutes=480

# =====================================================
# SERVER
# =====================================================

server.port=8081